In [2]:
import pandas as pd

df = pd.read_json('/content/delhi_metro_trips.json')
df.head()

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,None,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak

In [3]:
df.tail()

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
9995,126089,2022-07-20,RAJIV CHOWK,Shivaji Park,12.77,67.29,15.91,21.0,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20.0,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22.0,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18.0,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20.0,Single,off-peak

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         9888 non-null   object
 9   Remarks             8246 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 859.4+ KB

In [5]:
print(df.isnull().sum())

TripID                   0
Date                     0
From_Station             0
To_Station               0
Distance_km              0
Fare                     0
Cost_per_passenger       0
Passengers              90
Ticket_Type            112
Remarks               1754
dtype: int64

In [6]:
df['From_Station'] = df['From_Station'].str.strip().str.title()
df['To_Station'] = df['To_Station'].str.strip().str.title()

Remove extra spaces + fix capitalization in From_Station and To_Stations

In [7]:
df.tail()

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
9995,126089,2022-07-20,Rajiv Chowk,Shivaji Park,12.77,67.29,15.91,21.0,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20.0,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22.0,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18.0,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20.0,Single,off-peak

In [8]:
df['Ticket_Type'] = df['Ticket_Type'].fillna('Unknown')

filling missing values in Ticket type with "Unknown"

In [9]:
print(df.isnull().sum())

TripID                   0
Date                     0
From_Station             0
To_Station               0
Distance_km              0
Fare                     0
Cost_per_passenger       0
Passengers              90
Ticket_Type              0
Remarks               1754
dtype: int64

In [10]:
df

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,Rajiv Chowk,Shivaji Park,12.77,67.29,15.91,21.0,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20.0,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22.0,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18.0,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20.0,Single,off-peak

In [11]:
#df['Date'] = pd.to_datetime(df['Date'])

not needed since the format already in datetime format

In [12]:
df

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27.0,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23.0,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,Rajiv Chowk,Shivaji Park,12.77,67.29,15.91,21.0,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20.0,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22.0,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18.0,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20.0,Single,off-peak

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         10000 non-null  object
 9   Remarks             8246 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 859.4+ KB

In [14]:
#cols = ['Distance_km', 'Fare', 'Cost_per_passenger', 'Passengers']
#for col in cols:
#    df[col] = pd.to_numeric(df[col], errors='coerce')

in info its already mentioned as the numerical datas are clearly int and float. Good to proceed !!

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         10000 non-null  object
 9   Remarks             8246 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 859.4+ KB

In [17]:
df['Passengers'] = df['Passengers'].fillna(0).astype(int)

Passengers column is a count of passengers so changed to integer and missing values be 0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          10000 non-null  int64
 8   Ticket_Type         10000 non-null  object
 9   Remarks             8246 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 859.4+ KB

In [19]:
df

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,Rajiv Chowk,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [20]:
df['Remarks'] = df['Remarks'].fillna('Nil')

missing values in remarks been changed to "Nil"

In [21]:
df

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,Inderlok,Kashmere Gate,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,Model Town,Dilshad Garden,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,Kashmere Gate,Netaji Subhash Place,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,Chandni Chowk,Hauz Khas,4.02,144.13,14.98,27,Unknown,maintenance
4,144298,2022-11-06,Rajiv Chowk,Kalkaji Mandir,9.66,104.96,83.84,23,Single,off-peak
...,...,...,...,...,...,...,...,...,...,...
9995,126089,2022-07-20,Rajiv Chowk,Shivaji Park,12.77,67.29,15.91,21,Tourist Card,weekend
9996,128187,2022-07-27,Kalkaji Mandir,Kirti Nagar,1.64,153.93,46.47,20,Tourist Card,maintenance
9997,138131,2023-02-01,Hauz Khas,Central Secretariat,1.48,56.32,10.75,22,Tourist Card,festival
9998,135989,2022-08-06,Rajiv Chowk,Old Delhi,1.50,89.75,68.03,18,Single,weekend
9999,93474,2022-09-28,Noida City Centre,Janakpuri West,0.57,19.17,52.09,20,Single,off-peak

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          10000 non-null  int64
 8   Ticket_Type         10000 non-null  object
 9   Remarks             10000 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(2), object(4)
memory usage: 859.4+ KB

In [23]:
print(df.isnull().sum())

TripID                0
Date                  0
From_Station          0
To_Station            0
Distance_km           0
Fare                  0
Cost_per_passenger    0
Passengers            0
Ticket_Type           0
Remarks               0
dtype: int64

In [24]:
df.to_csv('/content/delhi_metro_trips.csv', index=False)